spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/schema_name
    username: test_user
    password: test_pswd
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      eclipselink:
        ddl-generation: none