server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://null:null/null
    username: null
    password: null
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect